### ISSUE TITLE
About Nodes：Convert .wav file to USoundWave

### ISSUE THREAD

**Issue by Liyi1998** [lucoiso/UEAzSpeech#163] opened 2023-03-23 08:04 UTC
Thankyou, i have a wav file ,it's path is"‪I:\GPT51\ttswav\369.wav".
I want use this nodes convert

FilePath:I:GPT51/ttswav/
FileName:369     (I tried it too "369.wav")
OutputModulePath:/Game/
RelativeOutputDirectory:Generated_Sounds
OutputAssetName:SW_Generated_Audio

but,ReturnValue is empty.
I hope to get your help.
I am a Chinese and my English level is very poor. Please forgive me.

**Comment by lucoiso** [comment] 2023-03-23 11:07
Hello! @Liyi1998  :)

Can you send me the logs?

Enable them in Project Settings -> Plugins -> AzSpeech -> Enable SDK Logs & Enable Internal Logs
Logs are generates in: PROJECT_DIRECTORY/Saved/Logs & PROJECT_DIRECTORY/Saved/Logs/AzSpeech

**Comment by Liyi1998** [comment] 2023-03-23 11:33
![image](https://user-images.githubusercontent.com/48345891/227191059-6fb0cbe0-8d08-4b74-860c-39a27eb7b8fa.png)
And I have turned on the relevant settings

**Comment by lucoiso** [comment] 2023-03-23 11:46
You can send me the GPTS.log. :)

The SW_Generated_Audio was generated correctly? The issue is occurring only with the function return? _I'll check locally here soon_

**Comment by Liyi1998** [comment] 2023-03-23 11:54
[GPT5.log](https://github.com/lucoiso/UEAzSpeech/files/11050373/GPT5.log)
这是GPT5.log      SW_ Generated_ Audio not generated       
![image](https://user-images.githubusercontent.com/48345891/227195822-b3ca0b79-b16d-404b-9d06-e328623d40bc.png)

**Comment by Liyi1998** [comment] 2023-03-23 11:57
According to the log description, 369.wav cannot be found, but it is in the folder at the path I specified

**Comment by lucoiso** [comment] 2023-03-23 14:00
Hi! @Liyi1998 

Found the issue! The content module checking is failing due to a wrong implementation, I'll send a correction.

You can avoid this error using **Game** instead of **/Game/** in Output Module parameter

**Comment by lucoiso** [comment] 2023-03-23 15:21
Closing this issue, the main problem was solved and merged. I'll check the warning related to 32bits wav files separated from this one.

**Closed as completed by lucoiso** 2023-03-23 15:21 UTC
Labels: bug
